# Generated by Django 5.2.5 on 2025-09-30 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(max_length=255)),
                ('prediction', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('protocol', models.FloatField()),
                ('fwd_packet_length_min', models.FloatField()),
                ('bwd_packet_length_min', models.FloatField()),
                ('flow_bytes', models.FloatField()),
                ('flow_iat_min', models.FloatField()),
                ('fwd_iat_mean', models.FloatField()),
                ('fwd_iat_min', models.FloatField()),
                ('bwd_iat_total', models.FloatField()),
                ('bwd_iat_mean', models.FloatField()),
                ('bwd_iat_max', models.FloatField()),
                ('bwd_iat_min', models.FloatField()),
                ('bwd_psh_flags', models.FloatField()),
                ('bwd_urg_flags', models.FloatField()),
                ('bwd_header_length', models.FloatField()),
                ('fwd_packets', models.FloatField()),
                ('bwd_packets', models.FloatField()),
                ('packet_length_min', models.FloatField()),
                ('packet_length_variance', models.FloatField()),
                ('fin_flag_count', models.FloatField()),
                ('syn_flag_count', models.FloatField()),
                ('psh_flag_count', models.FloatField()),
                ('ack_flag_count', models.FloatField()),
                ('urg_flag_count', models.FloatField()),
                ('cwe_flag_count', models.FloatField()),
                ('ece_flag_count', models.FloatField()),
                ('down_up_ratio', models.FloatField()),
                ('avg_fwd_segment_size', models.FloatField()),
                ('avg_bwd_segment_size', models.FloatField()),
                ('fwd_avg_bytes', models.FloatField()),
                ('fwd_avg_packets', models.FloatField()),
                ('fwd_avg_bulk_rate', models.FloatField()),
                ('bwd_avg_bytes', models.FloatField()),
                ('bwd_avg_packets', models.FloatField()),
                ('bwd_avg_bulk_rate', models.FloatField()),
                ('subflow_fwd_bytes', models.FloatField()),
                ('subflow_bwd_bytes', models.FloatField()),
                ('init_fwd_win_bytes', models.FloatField()),
                ('init_bwd_win_bytes', models.FloatField()),
                ('fwd_act_data_packets', models.FloatField()),
                ('fwd_seg_size_min', models.FloatField()),
                ('active_std', models.FloatField()),
                ('active_max', models.FloatField()),
                ('active_min', models.FloatField()),
                ('idle_std', models.FloatField()),
                ('idle_min', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
