# Generated by Django 5.2.5 on 2025-10-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtnc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
