# Generated by Django 5.1.9 on 2025-10-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtnc', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='packets',
            name='fwd_header_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packets',
            name='fwd_urg_flags',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packets',
            name='types',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
