# Generated by Django 5.1.9 on 2025-10-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtnc', '0003_packets_fwd_header_length_packets_fwd_urg_flags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packets',
            old_name='bwd_iat_mean',
            new_name='fwd_packet_length_std',
        ),
        migrations.AddField(
            model_name='packets',
            name='rst_flag_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packets',
            name='bwd_urg_flags',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
