# Generated by Django 5.1.9 on 2025-10-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtnc', '0004_rename_bwd_iat_mean_packets_fwd_packet_length_std_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packets',
            old_name='fwd_packet_length_std',
            new_name='bwd_iat_mean',
        ),
        migrations.RemoveField(
            model_name='packets',
            name='fwd_header_length',
        ),
        migrations.RemoveField(
            model_name='packets',
            name='fwd_urg_flags',
        ),
        migrations.RemoveField(
            model_name='packets',
            name='rst_flag_count',
        ),
        migrations.RemoveField(
            model_name='packets',
            name='types',
        ),
    ]
