# Generated by Django 5.1.9 on 2025-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtnc', '0005_rename_fwd_packet_length_std_packets_bwd_iat_mean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packets',
            old_name='bwd_avg_bytes',
            new_name='bwd_avg_bytes_bulk',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='bwd_avg_packets',
            new_name='bwd_avg_packets_bulk',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='bwd_iat_mean',
            new_name='bwd_packets_s',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='bwd_packets',
            new_name='flow_bytes_s',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='flow_bytes',
            new_name='fwd_avg_bytes_bulk',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='fwd_avg_bytes',
            new_name='fwd_avg_packets_bulk',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='fwd_avg_packets',
            new_name='fwd_header_length',
        ),
        migrations.RenameField(
            model_name='packets',
            old_name='fwd_packets',
            new_name='fwd_packets_s',
        ),
        migrations.AddField(
            model_name='packets',
            name='fwd_packet_length_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packets',
            name='fwd_urg_flags',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
