# Generated by Django 5.1.9 on 2025-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtnc', '0006_rename_bwd_avg_bytes_packets_bwd_avg_bytes_bulk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packets',
            name='types',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
